spring.application.name=ticket-system
spring.datasource.url=jdbc:mysql://192.168.64.3:3306/ticketsDB
spring.datasource.username=root
spring.datasource.password=gimlithedwarf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.security=DEBUG
