package com.grupo7.ticket_system.users;
import java.time.LocalDateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Repository;
import com.grupo7.ticket_system.models.User;


@Repository
public class UserRepository {

    private final JdbcTemplate template;

    UserRepository(JdbcTemplate template) {
        this.template = template;
    }

    public User saveUser(User user){
        //get postal code
        String sqltogetpostalcodeid= "SELECT id_codigo_postal FROM codigo_postal_direccion WHERE codigo_postal = ?";
        try {
            int postalCodeId = template.queryForObject(sqltogetpostalcodeid, int.class,user.getPostalCode());
            user.setPostalCodeId(postalCodeId);
        } catch (EmptyResultDataAccessException e) {
            throw new IllegalArgumentException("Invalid postal code");
        }
        //save user
        String sqltosaveuser= "INSERT INTO usuario (nombre_usuario,contrasena,rol,mail,pais_documento,tipo_documento,numero_documento,calle_direccion,numero_direccion, id_codigo_postal) VALUES (?,?,?,?,?,?,?,?,?,?)";
        template.update(sqltosaveuser,user.getUsername(),user.getPassword(),user.getRol(),user.getEmail(), user.getDocumentCountry(), user.getDocumentType(), user.getDocumentNumber(), 
                        user.getStreetAddress(), user.getNumberAddress(),user.getPostalCodeId());
        //get user id autogenerated in database
        String sqltogetuserid= "SELECT LAST_INSERT_ID()";        
        user.setUserId(template.queryForObject(sqltogetuserid, int.class));
        //save user as general_user
        String sqltosaveuseasgeneraluser= "INSERT INTO usuario_general(id_usuario, fecha_registro, estado_verificacion) VALUES (?,?,?)";
        template.update(sqltosaveuseasgeneraluser, user.getUserId(), LocalDateTime.now(), true);
        //save user phones
        String sqltosavephones= "INSERT INTO telefono(numero_telefono, id_usuario) VALUES (?,?)";
        for(String phone: user.getPhones()){
            template.update(sqltosavephones,phone,user.getUserId());
        }
        return user;
    }

    //check if the email exists in database
    public boolean existsByMail(String mail){
        String sqltofindbyemail= "SELECT COUNT(*) FROM usuario JOIN usuario_general ON usuario.id_usuario=usuario_general.id_usuario WHERE usuario.mail=?";
        return template.queryForObject(sqltofindbyemail, int.class, mail) >0;
    }

    //get object user by string username
    public UserDetails getUserByUsername(String username){
        String sqltogetuserbyusername= "SELECT nombre_usuario, contrasena, rol FROM usuario WHERE nombre_usuario= ?";
        return template.queryForObject(sqltogetuserbyusername, (rs,rownum)-> org.springframework.security.core.userdetails.User.withUsername(rs.getString("nombre_usuario")).password(rs.getString("contrasena")).roles(rs.getString("rol")).build(),username);
    }

    //get userId by string username
    public int getUserIdByUsername(String username){
        String sqltofinduserid= "SELECT id_usuario FROM usuario WHERE nombre_usuario= ?";
        return template.queryForObject(sqltofinduserid, int.class,username);
    }
}