package com.grupo7.ticket_system.users;
import java.time.LocalDateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Repository;
import com.grupo7.ticket_system.models.User;


@Repository
public class UserRepository {

    private final JdbcTemplate template;

    UserRepository(JdbcTemplate template) {
        this.template = template;
    }

    public User saveUser(User user){
        //get postal code
        String sqltogetpostalcodeid= "SELECT id_codigo_postal FROM codigo_postal_direccion WHERE codigo_postal = ?";
        try {
            int postalCodeId = template.queryForObject(sqltogetpostalcodeid, int.class,user.getPostalCode());
            user.setPostalCodeId(postalCodeId);
        } catch (EmptyResultDataAccessException e) {
            throw new IllegalArgumentException("Invalid postal code");
        }
        //save user
        String sqltosaveuser= "INSERT INTO usuario (nombre_usuario,contrasena,rol,mail,pais_documento,tipo_documento,numero_documento,calle_direccion,numero_direccion, id_codigo_postal) VALUES (?,?,?,?,?,?,?,?,?,?)";
        template.update(sqltosaveuser,user.getUsername(),user.getPassword(),user.getRol(),user.getEmail(), user.getDocumentCountry(), user.getDocumentType(), user.getDocumentNumber(), 
                        user.getStreetAddress(), user.getNumberAddress(),user.getPostalCodeId());
        //get user id autogenerated in database
        String sqltogetuserid= "SELECT LAST_INSERT_ID()";        
        user.setUserId(template.queryForObject(sqltogetuserid, int.class));
        //save user as general_user
        String sqltosaveuseasgeneraluser= "INSERT INTO usuario_general(id_usuario, fecha_registro, estado_verificacion) VALUES (?,?,?)";
        template.update(sqltosaveuseasgeneraluser, user.getUserId(), LocalDateTime.now(), true);
        //save user phones
        String sqltosavephones= "INSERT INTO telefono(numero_telefono, id_usuario) VALUES (?,?)";
        if (user.getPhones() != null) {
            for (String phone: user.getPhones()) {
                template.update(sqltosavephones, phone, user.getUserId());
            }
        }
        return user;
    }

    //check if the email exists in database
    public boolean existsByMail(String mail) {
        String sqltofindbyemail = "SELECT COUNT(*) FROM usuario WHERE mail=?"; //Consulta directamente la tabla usuario porque el mail tiene que ser unico a nivel usuario sin importar el rol
        return template.queryForObject(sqltofindbyemail, int.class, mail) > 0;
    }

    //get object user by string username
    public UserDetails getUserByUsername(String username){
        String sqltogetuserbyusername= "SELECT nombre_usuario, contrasena, rol FROM usuario WHERE nombre_usuario= ?";
        return template.queryForObject(sqltogetuserbyusername, (rs,rownum)-> org.springframework.security.core.userdetails.User.withUsername(rs.getString("nombre_usuario")).password(rs.getString("contrasena")).roles(rs.getString("rol")).build(),username);
    }

    //get userId by string username
    public int getUserIdByUsername(String username){
        String sqltofinduserid= "SELECT id_usuario FROM usuario WHERE nombre_usuario= ?";
        return template.queryForObject(sqltofinduserid, int.class,username);
    }

    public List<Map<String, Object>> findTicketsByUserId(int userId) {
        String sql = """
            SELECT e.id_entrada,
                   e.id_evento,
                   ev.fecha_evento,
                   es.nombre_estadio,
                   s.letra_sector,
                   e.qr_entrada,
                   e.cantidad_transferencias_realizadas,
                   e.id_dispositivo
            FROM entrada e
            JOIN evento ev ON ev.id_evento = e.id_evento
            JOIN estadio es ON es.id_estadio = e.id_estadio
            LEFT JOIN sector s ON s.id_sector = e.id_sector
            WHERE e.id_usuario = ?
            ORDER BY ev.fecha_evento DESC, e.id_entrada DESC
            """;
        return template.queryForList(sql, userId);
    }

    public List<Map<String, Object>> findSalesByUserId(int userId) {
        String sql = """
            SELECT v.id_venta,
                   v.fecha_venta,
                   v.estado,
                   v.monto_total,
                   v.porcentaje_comision_aplicado,
                   COUNT(e.id_entrada) AS cantidad_entradas
            FROM venta v
            LEFT JOIN entrada e ON e.id_venta = v.id_venta
            WHERE v.id_usuario = ?
            GROUP BY v.id_venta, v.fecha_venta, v.estado, v.monto_total, v.porcentaje_comision_aplicado
            ORDER BY v.fecha_venta DESC
            """;
        return template.queryForList(sql, userId);
    }

    public List<Map<String, Object>> findTransfersByUserId(int userId) {
        String sql = """
            SELECT t.fecha_transferencia,
                   t.estado_transferencia,
                   t.id_entrada,
                   envia.nombre_usuario AS usuario_envia,
                   recibe.nombre_usuario AS usuario_recibe
            FROM transferencia t
            JOIN usuario envia ON envia.id_usuario = t.id_usuario_envia
            JOIN usuario recibe ON recibe.id_usuario = t.id_usuario_recibe
            WHERE t.id_usuario_envia = ? OR t.id_usuario_recibe = ?
            ORDER BY t.fecha_transferencia DESC
            """;
        return template.queryForList(sql, userId, userId);
    }

    public List<Map<String, Object>> findTopBuyers() {
        String sql = """
            SELECT u.id_usuario,
                   u.nombre_usuario,
                   u.mail,
                   COUNT(DISTINCT v.id_venta) AS cantidad_compras,
                   COUNT(e.id_entrada) AS cantidad_entradas
            FROM usuario u
            JOIN venta v ON v.id_usuario = u.id_usuario
            LEFT JOIN entrada e ON e.id_venta = v.id_venta
            GROUP BY u.id_usuario, u.nombre_usuario, u.mail
            ORDER BY cantidad_entradas DESC, cantidad_compras DESC
            LIMIT 10
            """;
        return template.queryForList(sql);
    }
}